"""add investor columns

Revision ID: c957f57434e3
Revises: 3142e0aab244
Create Date: 2026-08-28 19:42:47.698701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c957f57434e3'
down_revision: Union[str, None] = '3142e0aab244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('investor_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='jobstatus', native_enum=False, length=50), nullable=True))
    op.add_column('analysis_jobs', sa.Column('investor_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analysis_jobs', sa.Column('investor_error_message', sa.Text(), nullable=True))
    op.alter_column('analysis_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('analysis_jobs', 'depth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.alter_column('analysis_jobs', 'depth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('analysis_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('analysis_jobs', 'investor_error_message')
    op.drop_column('analysis_jobs', 'investor_result_json')
    op.drop_column('analysis_jobs', 'investor_status')
    # ### end Alembic commands ###
